export const meta = {
  name: 'um-resync-parallel-sweep',
  description: 'Safe parallel read-only resync analysis (eval-perpetual-safe: resync tree has NO eval session) — translation-zh apply-prep (resolve spliceRegion bootstrap + 5 fence-wrap verbatim) + UM-LINT raw capture + rule summary. Apply is serial in main session (rule 2/3).',
  phases: [{ title: 'Parallel resync analysis', detail: '2 read-only agents on resync: S-tz-prep + S-lint2' }],
  whenToUse: 'Next session: run via Workflow({scriptPath}) to produce translation-zh apply patch + UM-LINT raw/rule-summary in parallel (safe — resync, no eval collision), then apply serially on resync.',
}

const IRON = 'ENVIRONMENT IRON LAWS: Built-in Read/Write/Edit/Bash/Grep/Glob are BLOCKED — use ONLY mcp__local__* tools (read_file/bash/write_file/list_dir/stat/glob). mcp__local__grep is UNRELIABLE → use grep -rEn inside mcp__local__bash; rg and grep -P do NOT exist (BSD grep only). node v24 MANDATORY: prefix EVERY bash with: export PATH="/usr/local/bin:$PATH" (yields v24.15.0; system default v25 crashes tsdown/rolldown). Verify with node -v. Shell is sh NOT bash (no <(...); use temp files + sort/comm). READ-ONLY: no build/gen-*/commit/modify repo files; write ONLY /tmp. Runner flaky on long calls: keep bash SHORT (long content → mcp__local__write_file to /tmp, then short bash); write /tmp INCREMENTALLY so partial results survive. RESYNC tree: /Users/mckenzie/workspace/dsh-resync (NO eval session here — safe to read + run oxlint lint; do NOT touch .git/index.lock, .worktrees/, wayfinder/evaluation/). STEP 0 probe FIRST: mcp__local__bash run: export PATH="/usr/local/bin:$PATH"; echo PROBE_ALIVE; node -v — if it fails or node is not v24.x, STOP and return exactly: NO_MCP_LOCAL_ACCESS_OR_BAD_NODE with what you saw. Do not proceed.'

const TZ = IRON + '\n\n=== TASK: translation-zh apply-prep (Cordis region-splice, user-locked 2026-09-11) ===\nResolve the bootstrap blocker + produce the precise apply patch for scripts/gen-doc-graphs.ts on the resync tree.\n\nSTEP 1 — read spliceRegion: mcp__local__bash: cd /Users/mckenzie/workspace/dsh-resync && grep -n "export function spliceRegion" scripts/gen-cordis-catalog.ts; then sed -n "<start>,<end>p" to read its FULL body (the function is at line ~920, NOT :747 as a prior subagent guessed). Determine: does spliceRegion INSERT the region if the BEGIN/END fences are absent (insert-if-absent), or does it only REPLACE existing fenced pairs? This is the bootstrap blocker — the 5 existing docs/*.zh.md files were hand-translated from fence-less English; the first regen after the change must INSERT fences into them.\n\nSTEP 2 — read the 5 render fns in scripts/gen-doc-graphs.ts for verbatim old text to fence-wrap: renderCapabilitySeams (~:744, mermaid + services table), renderEventRelations (~:1296, mermaid + producer/consumer matrix), renderLifecycle (~:1343, turn/step mermaid ONLY — prose stays unfenced), renderToolPipeline (~:1427, pipeline mermaid ONLY), renderIndex (~:1505, the |Graph|Mode| index table ONLY — intro prose unfenced). For each, identify the EXACT structured block (mermaid/tables) to wrap in BEGIN GENERATED <slug> / END GENERATED <slug> fences. Give verbatim old text + the fenced new text + the slug name.\n\nSTEP 3 — read scripts/translation-pairing.ts partitionGeneratedRegions + fence grammar (~:21-35): confirm the fence format (BEGIN/END GENERATED <slug>, well-formed, slug-matched, else partitionGeneratedRegions throws) the render fns must produce.\n\nSTEP 4 — write /tmp/s3-apply-prep.md incrementally: (a) the spliceRegion insert-vs-replace VERDICT + the exact lines from its body proving it; (b) if replace-only, the one-time migration helper needed (insert fences into the 5 .zh.md first); (c) the 5 fence-wrap edits (verbatim old → fenced new, per render fn, with slug names); (d) the 3a imports (blobHash/partitionGeneratedRegions/renderPairMeta from ./translation-pairing.ts + maybeRecordPair/spliceRegion from ./gen-cordis-catalog.ts) + 3c main() rewrite (PAIRED_DOCS Set of 5 docs/* + splice zh via partitionGeneratedRegions(doc.content).regions → spliceRegion + maybeRecordPair(doc.rel, before); 3 composition files do NOT pair).\n\nRETURN: short summary — spliceRegion verdict (insert-if-absent or replace-only + migration helper needed?), the 5 fence-wrap slugs, any surprise, path /tmp/s3-apply-prep.md. Deliverable in /tmp, NOT your return text.'

const LINT = IRON + '\n\n=== TASK: UM-LINT raw capture + rule-level summary (re-triage on resync) ===\nA prior subagent (S-LINT) measured master (wrong tree — master is pre-merge, 0 findings). UM-LINT 93 are on the post-merge tree. Re-measure on RESYNC + produce raw + rule summary.\n\nSTEP 1 — mcp__local__bash: cd /Users/mckenzie/workspace/dsh-resync && export PATH="/usr/local/bin:$PATH" && pnpm run lint:contracts-ready > /tmp/lint-resync-wf.txt 2>&1; echo "lint_exit=$?" >> /tmp/lint-resync-wf.txt; wc -l /tmp/lint-resync-wf.txt. (lint:contracts-ready = tsx scripts/run-oxlint.ts . with .oxlintrc.json, read-only oxlint scan ~35s. If the call drops, retry — idempotent. Do NOT run pnpm run lint — that runs build:lib:host first which writes lib/.tsbuildinfo = read-only violation.)\n\nSTEP 2 — parse /tmp/lint-resync-wf.txt in chunks (do NOT cat inline — use grep -n / sed -n / wc -l). Count findings per rule: no-unsafe-call, no-unsafe-member-access, no-unsafe-assignment, no-unsafe-argument, no-unnecessary-type-assertion, no-unsafe-return, max-len, unbound-method, no-unnecessary-condition, no-deprecated, others. Total should be ~92.\n\nSTEP 3 — write /tmp/slint2-summary.md: (a) total count + exit code; (b) per-rule count table; (c) FP-bucket vs REAL-bucket split (FP = no-unsafe-* family ~85/92, the Cordis type-aware inject-d service-handle false-positives; REAL = no-unnecessary-type-assertion ~5 [ctx as never — SEMANTIC change, do NOT auto-strip], max-len ~2 [mechanical wrap], no-deprecated ~1 [API migration]); (d) the disable-directive form (// eslint-disable-next-line typescript/<rule> -- <reason>, repo-recognized at packages/host/apiproxy/src/api-proxy.ts:3364; file-level /* eslint-disable */ for clustered); (e) a sampling of 5-10 specific findings (file:line:col | rule | one-line FP/real guess) to calibrate the next session per-finding triage.\n\nNOTE: full per-finding triage (92 disable-directives) is the NEXT session apply-prep — this workflow produces raw + rule summary + a sample, NOT all 92.\n\nRETURN: short summary — total count, per-rule top 5, FP-vs-REAL bucket split, the 5-10 sample findings, path /tmp/slint2-summary.md + /tmp/lint-resync-wf.txt. Deliverable in /tmp.'

phase('Parallel resync analysis')
const [tz, lint] = await parallel([
  () => agent(TZ, { label: 'S-tz-prep', phase: 'Parallel resync analysis', agentType: 'general-purpose' }),
  () => agent(LINT, { label: 'S-lint2', phase: 'Parallel resync analysis', agentType: 'general-purpose' }),
])

return { tzPrep: tz, lintSummary: lint }
